// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AvatarController from "./avatar_controller"
application.register("avatar", AvatarController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import TaskDropdownController from "./task_dropdown_controller"
application.register("task-dropdown", TaskDropdownController)
